[package]
name = "pixi_byte"
version = "0.1.0"
edition = "2024"
authors = ["OriniumBrowser DeveloperTeam"]
license = "MIT OR Apache-2.0"
description = "A JavaScript engine for OriniumBrowser"
repository = "https://github.com/oriniumbrowser/pixi_byte"

[[bench]]
harness = false
name = "vm_bench"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
regex = "1.12"
rustc-hash = "2.1"

[dev-dependencies]
criterion = "0.8"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
